### ISSUE TITLE
Create a Main Menu

### ISSUE THREAD

**Issue by Bashakj49** [gwillemssen/Cat-Game#106]
Settings for accessibility requested

**Comment by Lilysium** [comment]
- [x] Draft
- [x] Model 3D Env
- [x] Script Functionality
- [x] Ambience + Lighting
- [x] Connect to main scene
- [ ] Cat Petting starts game

**Comment by Lilysium** [comment]
![Image](https://user-images.githubusercontent.com/110079778/221350963-7e916909-fd7e-4858-b367-e48488af9019.png)



![Image](https://user-images.githubusercontent.com/110079778/221350970-bd23f187-6266-44ad-931c-4e4dc3a305c5.png)
