### ISSUE TITLE
Asset Creation: Kitchen Décor

### ISSUE THREAD

**Issue by Lilysium** [gwillemssen/Cat-Game#128]
- [x] Models:
    - [x] Fruit Basket
    - [x] Plates
    - [x] Fake Snacks & Foods such as cereal and chips

- [x] Texture:
    - [x] Fruit Basket
    - [x] Plates
    - [x] Fake Snacks & Foods such as cereal and chips

- [x] Prefabs:
    - [x] Fruit Basket
    - [x] Plates
    - [x] Fake Snacks & Foods such as cereal and chips

**Comment by adrianggc** [comment]
Starting on fruit basket and plates
