### ISSUE TITLE
Friday to-do list, Programming

### ISSUE THREAD

**Issue by Madman283** [gwillemssen/Cat-Game#38]
- Crouching
- Enemy Patrolling constant
- Change/Update Audio Script
- Change "FindObjectofType" to Singleton

Optional for this week:
- if spotted enemy will call police and add countdown before they lose
- if spotted enemy will leave to another room to get a weapon(shotgun, close range is a must)
- if cat is pet the wrong way it will run to a new location

**Comment by Kratosflare** [comment]
Crouching and patrolling is done. "FindObjectofType" fully converted to singleton
