### ISSUE TITLE
Complete distressed bed model, texture and import

### ISSUE THREAD

**Issue by Bashakj49** [gwillemssen/Cat-Game#46]
If time permits after completing the animation state controller, I will try and finish modeling/texturing the bed 
![Distressed_BedwFrame_Ver_1](https://user-images.githubusercontent.com/56273882/198864852-aa9e4c5e-38a1-4ac5-8331-9b901f39e5a8.jpg)

**Comment by Lilysium** [comment]
@Bashakj49 checking in to see how this is going
