### ISSUE TITLE
Asset Creation: Throwable Props Mega Thread

### ISSUE THREAD

**Issue by gwillemssen** [gwillemssen/Cat-Game#71]
- [x] Models:
     - [x]  Cup
     - [x] Bottle
     - [x] Mug
     - [x] Snack Bowl
     - [x] TV Remote
     - [x] Toaster
     - [x] Phone
     - [x] Pill Bottles
     - [x] Coaster
     - [x] Cutting Board
     - [x] Shampoo Bottle
     - [x] Conditioner Bottle
     - [x] Photo Frames
     - [x] Vase
- [ ] Textures:
     - [x]  Cup
     - [x] Bottle
     - [x] Mug
     - [x] Snack Bowl
     - [x] TV Remote
     - [x] Toaster
     - [x] Phone
     - [x] Pill Bottles
     - [x] Coaster
     - [x] Cutting Board
     - [x] Shampoo Bottle
     - [x] Conditioner Bottle
     - [x] Photo Frames
     - [ ] Vase

- [ ] Prefab in Unity
     - [x]  Cup
     - [x] Bottle
     - [x] Mug
     - [x] Snack Bowl
     - [x] TV Remote
     - [x] Toaster
     - [x] Phone
     - [x] Pill Bottles
     - [x] Coaster
     - [x] Cutting Board
     - [x] Shampoo Bottle
     - [x] Conditioner Bottle
     - [ ] Photo Frames
     - [ ] Vase

Additional Implementation:
- [ ] Convert fragile objects to breakable state
     - [ ] Bottle
     - [ ] Mug
     - [ ] Photo Frame
     - [x] Vase

**Comment by Lilysium** [comment]
@Ryztiq could use a video demo to reference how to convert an object into a breakable within blender.

**Comment by Lilysium** [comment]
Adding all objects listed in the scene as throwables into this list.
